public class FindTheDifference {
    //Given two strings s and t which consist of only lowercase letters.
    //
    //String t is generated by random shuffling string s and then add one more letter at a random position.
    //
    //Find the letter that was added in t.
    //
    //Example:
    //
    //Input:
    //s = "abcd"
    //t = "abcde"
    //
    //Output:
    //e
    //
    //Explanation:
    //'e' is the letter that was added.
    public static void main(String[] args) {

    }
    public char findTheDifference(String s, String t) {
        int[] letters = new int[26];

        char ans = 0;
        for (char c :t.toCharArray()){
            letters[c-'a']++;
        }
        for (char c: s.toCharArray()){
            letters[c-'a']--;
        }
        for (int i = 0; i<26; i++){
            if (letters[i]>0){
                ans = (char) ('a'+i);
            }
        }
        return ans;
    }
}
